### ISSUE TITLE
require docopt breaks connect

### ISSUE THREAD

**Issue by Vrtak-CZ** [docopt/docopt.coffee#4]
If I just require docopt connect throws error

```
TypeError: Property 'handle' of object #<Object> is not a function
    at next (/home/vrtak-cz/Workspace/Vrtak-CZ/servit/node_modules/connect/lib/proto.js:190:15)
    at Object.logger (/home/vrtak-cz/Workspace/Vrtak-CZ/servit/node_modules/connect/lib/middleware/logger.js:156:5)
    at next (/home/vrtak-cz/Workspace/Vrtak-CZ/servit/node_modules/connect/lib/proto.js:190:15)
    at Object.favicon [as handle] (/home/vrtak-cz/Workspace/Vrtak-CZ/servit/node_modules/connect/lib/middleware/favicon.js:78:7)
    at next (/home/vrtak-cz/Workspace/Vrtak-CZ/servit/node_modules/connect/lib/proto.js:190:15)
    at Function.app.handle (/home/vrtak-cz/Workspace/Vrtak-CZ/servit/node_modules/connect/lib/proto.js:198:3)
    at Server.app (/home/vrtak-cz/Workspace/Vrtak-CZ/servit/node_modules/connect/lib/connect.js:66:31)
    at Manager.handleRequest (/home/vrtak-cz/Workspace/Vrtak-CZ/servit/node_modules/socket.io/lib/manager.js:564:28)
    at Server.<anonymous> (/home/vrtak-cz/Workspace/Vrtak-CZ/servit/node_modules/socket.io/lib/manager.js:118:10)
    at Server.EventEmitter.emit (events.js:126:20)
```

**Comment by Vrtak-CZ** [comment]
I think this should be because docopt manipulate with global Array.toString method.

**Comment by sonwell** [comment]
Ok, we're no longer overwriting Array.toString.

**Comment by keleshev** [comment]
@sonwell, welcome back :-)
